// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cm_dm_h)
#define octave_mx_cm_dm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (ComplexMatrix, ComplexMatrix, DiagMatrix, OCTAVE_API)
#endif
