// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cnda_nda_h)
#define octave_mx_cnda_nda_h 1
#include "octave-config.h"
#include "CNDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (ComplexNDArray, ComplexNDArray, NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (ComplexNDArray, NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (ComplexNDArray, NDArray, OCTAVE_API)
#endif
