// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cdm_s_h)
#define octave_mx_cdm_s_h 1
#include "octave-config.h"
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (ComplexDiagMatrix, ComplexDiagMatrix, double, OCTAVE_API)
#endif
