// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cs_nda_h)
#define octave_mx_cs_nda_h 1
#include "octave-config.h"
#include "CNDArray.h"
#include "oct-cmplx.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (ComplexNDArray, Complex, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (Complex, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (Complex, NDArray, OCTAVE_API)
#endif
