// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cm_cdm_h)
#define octave_mx_cm_cdm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (ComplexMatrix, ComplexMatrix, ComplexDiagMatrix, OCTAVE_API)
#endif
