// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_dm_cs_h)
#define octave_mx_dm_cs_h 1
#include "octave-config.h"
#include "CDiagMatrix.h"
#include "dDiagMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (ComplexDiagMatrix, DiagMatrix, Complex, OCTAVE_API)
#endif
