// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcdm_fs_h)
#define octave_mx_fcdm_fs_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (FloatComplexDiagMatrix, FloatComplexDiagMatrix, float, OCTAVE_API)
#endif
