// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcdm_fdm_h)
#define octave_mx_fcdm_fdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
DMDM_BIN_OP_DECLS (FloatComplexDiagMatrix, FloatComplexDiagMatrix, FloatDiagMatrix, OCTAVE_API)
#endif
