// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fs_fcdm_h)
#define octave_mx_fs_fcdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatComplexDiagMatrix, float, FloatComplexDiagMatrix, OCTAVE_API)
#endif
