// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcs_fdm_h)
#define octave_mx_fcs_fdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "oct-cmplx.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatComplexDiagMatrix, FloatComplex, FloatDiagMatrix, OCTAVE_API)
#endif
