// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fnda_fcnda_h)
#define octave_mx_fnda_fcnda_h 1
#include "octave-config.h"
#include "fCNDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (FloatComplexNDArray, FloatNDArray, FloatComplexNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (FloatNDArray, FloatComplexNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (FloatNDArray, FloatComplexNDArray, OCTAVE_API)
#endif
