// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcm_pm_h)
#define octave_mx_fcm_pm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
MPM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexMatrix, PermMatrix, OCTAVE_API)
#endif
