// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i16_ui16nda_h)
#define octave_mx_i16_ui16nda_h 1
#include "octave-config.h"
#include "oct-inttypes.h"
#include "uint16NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_int16, uint16NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int16, uint16NDArray, OCTAVE_API)
#endif
