// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i32_nda_h)
#define octave_mx_i32_nda_h 1
#include "octave-config.h"
#include "int32NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int32NDArray, octave_int32, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_int32, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int32, NDArray, OCTAVE_API)
#endif
