// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i16nda_ui16_h)
#define octave_mx_i16nda_ui16_h 1
#include "octave-config.h"
#include "int16NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (int16NDArray, octave_uint16, OCTAVE_API)
NDS_BOOL_OP_DECLS (int16NDArray, octave_uint16, OCTAVE_API)
#endif
