// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i64nda_ui64_h)
#define octave_mx_i64nda_ui64_h 1
#include "octave-config.h"
#include "int64NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (int64NDArray, octave_uint64, OCTAVE_API)
NDS_BOOL_OP_DECLS (int64NDArray, octave_uint64, OCTAVE_API)
#endif
