// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i8_i16nda_h)
#define octave_mx_i8_i16nda_h 1
#include "octave-config.h"
#include "oct-inttypes.h"
#include "int16NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_int8, int16NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int8, int16NDArray, OCTAVE_API)
#endif
