// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i8nda_ui32nda_h)
#define octave_mx_i8nda_ui32nda_h 1
#include "octave-config.h"
#include "int8NDArray.h"
#include "uint32NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (int8NDArray, uint32NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int8NDArray, uint32NDArray, OCTAVE_API)
#endif
