// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i16nda_ui64nda_h)
#define octave_mx_i16nda_ui64nda_h 1
#include "octave-config.h"
#include "int16NDArray.h"
#include "uint64NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (int16NDArray, uint64NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int16NDArray, uint64NDArray, OCTAVE_API)
#endif
