// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_m_cm_h)
#define octave_mx_m_cm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "dMatrix.h"
#include "mx-op-decl.h"
MM_BIN_OP_DECLS (ComplexMatrix, Matrix, ComplexMatrix, OCTAVE_API)
MM_CMP_OP_DECLS (Matrix, ComplexMatrix, OCTAVE_API)
MM_BOOL_OP_DECLS (Matrix, ComplexMatrix, OCTAVE_API)
#endif
