// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_m_dm_h)
#define octave_mx_m_dm_h 1
#include "octave-config.h"
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (Matrix, Matrix, DiagMatrix, OCTAVE_API)
#endif
