// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_nda_i32nda_h)
#define octave_mx_nda_i32nda_h 1
#include "octave-config.h"
#include "int32NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int32NDArray, NDArray, int32NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (NDArray, int32NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (NDArray, int32NDArray, OCTAVE_API)
#endif
