// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_s_cnda_h)
#define octave_mx_s_cnda_h 1
#include "octave-config.h"
#include "CNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (ComplexNDArray, double, ComplexNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (double, ComplexNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (double, ComplexNDArray, OCTAVE_API)
#endif
