// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_s_ui16nda_h)
#define octave_mx_s_ui16nda_h 1
#include "octave-config.h"
#include "uint16NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint16NDArray, double, uint16NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (double, uint16NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (double, uint16NDArray, OCTAVE_API)
#endif
