// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui16_ui32nda_h)
#define octave_mx_ui16_ui32nda_h 1
#include "octave-config.h"
#include "oct-inttypes.h"
#include "uint32NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_uint16, uint32NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint16, uint32NDArray, OCTAVE_API)
#endif
