// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui16nda_i8_h)
#define octave_mx_ui16nda_i8_h 1
#include "octave-config.h"
#include "uint16NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint16NDArray, octave_int8, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint16NDArray, octave_int8, OCTAVE_API)
#endif
