// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui16nda_i16nda_h)
#define octave_mx_ui16nda_i16nda_h 1
#include "octave-config.h"
#include "uint16NDArray.h"
#include "int16NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (uint16NDArray, int16NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint16NDArray, int16NDArray, OCTAVE_API)
#endif
