// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui64nda_fnda_h)
#define octave_mx_ui64nda_fnda_h 1
#include "octave-config.h"
#include "uint64NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint64NDArray, uint64NDArray, FloatNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (uint64NDArray, FloatNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint64NDArray, FloatNDArray, OCTAVE_API)
#endif
