// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui8nda_i8nda_h)
#define octave_mx_ui8nda_i8nda_h 1
#include "octave-config.h"
#include "uint8NDArray.h"
#include "int8NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (uint8NDArray, int8NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint8NDArray, int8NDArray, OCTAVE_API)
#endif
