// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui8nda_fs_h)
#define octave_mx_ui8nda_fs_h 1
#include "octave-config.h"
#include "uint8NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint8NDArray, uint8NDArray, float, OCTAVE_API)
NDS_CMP_OP_DECLS (uint8NDArray, float, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint8NDArray, float, OCTAVE_API)
#endif
