// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui64nda_ui8_h)
#define octave_mx_ui64nda_ui8_h 1
#include "octave-config.h"
#include "uint64NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint64NDArray, octave_uint8, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint64NDArray, octave_uint8, OCTAVE_API)
#endif
