// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui32_ui8nda_h)
#define octave_mx_ui32_ui8nda_h 1
#include "octave-config.h"
#include "oct-inttypes.h"
#include "uint8NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_uint32, uint8NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint32, uint8NDArray, OCTAVE_API)
#endif
