// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui8_fnda_h)
#define octave_mx_ui8_fnda_h 1
#include "octave-config.h"
#include "uint8NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint8NDArray, octave_uint8, FloatNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_uint8, FloatNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint8, FloatNDArray, OCTAVE_API)
#endif
