// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui32_i32nda_h)
#define octave_mx_ui32_i32nda_h 1
#include "octave-config.h"
#include "oct-inttypes.h"
#include "int32NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_uint32, int32NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint32, int32NDArray, OCTAVE_API)
#endif
