// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui32nda_i32_h)
#define octave_mx_ui32nda_i32_h 1
#include "octave-config.h"
#include "uint32NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint32NDArray, octave_int32, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint32NDArray, octave_int32, OCTAVE_API)
#endif
