// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_cm_sm_h)
#define octave_smx_cm_sm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
#include "mx-cm-s.h"
#include "mx-s-cm.h"
#include "mx-cm-m.h"
#include "mx-m-cm.h"
#include "mx-cnda-s.h"
#include "mx-s-cnda.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, ComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_MSM_CMP_OP_DECLS (ComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (ComplexMatrix, SparseMatrix, OCTAVE_API)
#endif
