// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_cm_scm_h)
#define octave_smx_cm_scm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, ComplexMatrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_CMP_OP_DECLS (ComplexMatrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (ComplexMatrix, SparseComplexMatrix, OCTAVE_API)
#endif
