// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_m_scm_h)
#define octave_smx_m_scm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dMatrix.h"
#include "mx-m-cs.h"
#include "mx-cs-m.h"
#include "mx-m-cm.h"
#include "mx-cm-m.h"
#include "mx-nda-cs.h"
#include "mx-cs-nda.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, Matrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_CMP_OP_DECLS (Matrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (Matrix, SparseComplexMatrix, OCTAVE_API)
#endif
