// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_scm_m_h)
#define octave_smx_scm_m_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dMatrix.h"
#include "mx-cs-m.h"
#include "mx-m-cs.h"
#include "mx-cm-m.h"
#include "mx-m-cm.h"
#include "mx-cs-nda.h"
#include "mx-nda-cs.h"
#include "Sparse-op-defs.h"
SPARSE_SMM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, Matrix, OCTAVE_API)
SPARSE_SMM_CMP_OP_DECLS (SparseComplexMatrix, Matrix, OCTAVE_API)
SPARSE_SMM_BOOL_OP_DECLS (SparseComplexMatrix, Matrix, OCTAVE_API)
#endif
