// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_sm_scm_h)
#define octave_smx_sm_scm_h 1
#include "octave-config.h"
#include "CSparse.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMSM_BIN_OP_DECLS (SparseComplexMatrix, SparseComplexMatrix, SparseMatrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_SMSM_CMP_OP_DECLS (SparseMatrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_SMSM_BOOL_OP_DECLS (SparseMatrix, SparseComplexMatrix, OCTAVE_API)
#endif
