// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_ccv_s_h)
#define octave_vx_ccv_s_h 1
#include "octave-config.h"
#include "CColVector.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (ComplexColumnVector, ComplexColumnVector, double, OCTAVE_API)
#endif
