// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_cs_cv_h)
#define octave_vx_cs_cv_h 1
#include "octave-config.h"
#include "CColVector.h"
#include "oct-cmplx.h"
#include "dColVector.h"
#include "mx-op-decl.h"
SV_BIN_OP_DECLS (ComplexColumnVector, Complex, ColumnVector, OCTAVE_API)
#endif
