// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_crv_s_h)
#define octave_vx_crv_s_h 1
#include "octave-config.h"
#include "CRowVector.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (ComplexRowVector, ComplexRowVector, double, OCTAVE_API)
#endif
