// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_crv_rv_h)
#define octave_vx_crv_rv_h 1
#include "octave-config.h"
#include "CRowVector.h"
#include "dRowVector.h"
#include "mx-op-decl.h"
VV_BIN_OP_DECLS (ComplexRowVector, ComplexRowVector, RowVector, OCTAVE_API)
#endif
