// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcrv_frv_h)
#define octave_vx_fcrv_frv_h 1
#include "octave-config.h"
#include "fCRowVector.h"
#include "fRowVector.h"
#include "mx-op-decl.h"
VV_BIN_OP_DECLS (FloatComplexRowVector, FloatComplexRowVector, FloatRowVector, OCTAVE_API)
#endif
