// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcrv_fs_h)
#define octave_vx_fcrv_fs_h 1
#include "octave-config.h"
#include "fCRowVector.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (FloatComplexRowVector, FloatComplexRowVector, float, OCTAVE_API)
#endif
