// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcv_fccv_h)
#define octave_vx_fcv_fccv_h 1
#include "octave-config.h"
#include "fCColVector.h"
#include "fColVector.h"
#include "mx-op-decl.h"
VV_BIN_OP_DECLS (FloatComplexColumnVector, FloatColumnVector, FloatComplexColumnVector, OCTAVE_API)
#endif
